export const skills = [
  {
    category: "AI / ML / GenAI",
    skills: [
      "Python",
      "LangChain",
      "LLMs",
      "RAG",
      "AI Agents",
      "Hugging Face Transformers",
      "PyTorch",
      "Scikit-learn",
      "MLflow",
      "Vector Search",
      "Text Embeddings",
      "OpenAI Models",
      "Garak",
    ],
  },
  {
    category: "Data Engineering",
    skills: [
      "Azure Databricks",
      "PySpark",
      "Azure Data Factory",
      "Azure Storage",
      "ADLS",
      "ETL / ELT",
      "Data Ingestion",
      "Data Transformation",
      "SQL",
    ],
  },
  {
    category: "MLOps / DevOps",
    skills: [
      "Docker",
      "Kubernetes (AKS)",
      "Azure DevOps Pipelines",
      "GitHub Actions",
      "CI/CD",
      "Automated Testing",
      "Static Analysis",
      "ARM Templates",
      "Azure CLI",
    ],
  },
  {
    category: "Cloud — Azure",
    skills: [
      "Azure ML",
      "Azure AI Search",
      "Azure Functions",
      "Azure Container Instances",
      "Azure Container Registry",
      "Azure Web Apps",
      "Azure Monitor",
      "Azure AD",
    ],
  },
  {
    category: "Backend / APIs",
    skills: [
      "FastAPI",
      "REST APIs",
      "Linux",
      "Bash",
      "Git",
      "Postman",
      "VS Code",
    ],
  },
  {
    category: "Mathematics",
    skills: [
      "Linear Algebra",
      "Multivariable Calculus",
      "Probability & Statistics",
      "Optimization Theory",
    ],
  },
  {
    category: "Security",
    skills: [
      "Cybersecurity Fundamentals",
      "OWASP",
      "AI / LLM Security",
      "Prompt Injection Defence",
      "Azure Security Center",
    ],
  },
] as const;
